version: '3.8'

services:
  frontend:
    build: ./frontend   # ✅ Ensure this matches the actual folder name
    container_name: frontend_container
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/userdata
    volumes:
      - ./backend:/app
      - /app/node_modules

  mongodb:
    image: mongo:6
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: