version: '3.8'

services:
  frontend:
    build: ./Frontend
    container_name: frontend_container
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - EMAIL_USER=services.psatech@gmail.com
      - EMAIL_PASS=lzis bjha poip rzzs

  mongo:
    image: mongo:5.0
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: